game = "ck3"
game_path = ""
mod_path = ""

[cache]
  enabled = true
  dir = ".pdxl/cache"
  lru_cap = 256

[lint]
  context = 0

[scan]
  ignore_dirs = ["licenses"]
  ignore_files = ["credits.txt", "checksum_manifest.txt", "guids.txt", "license.txt", "ofl.txt"]
