//! EU5 script-documentation tables — empty until the game's doc dumps are
//! generated by `pdxl-gamedocs`' `gen-tables` (same pipeline as CK3).

pub use pdxl_gamedocs::rows::{DocRow, LinkRow, ModifierRow, ScopeTypeRow};
pub use pdxl_gui::datafn::{DataFnKind, DataFnRow};

pub const TRIGGERS: &[DocRow] = &[];
pub const EFFECTS: &[DocRow] = &[];
pub const MODIFIERS: &[ModifierRow] = &[];
pub const SCOPE_LINKS: &[LinkRow] = &[];
pub const CODE_SAVED_SCOPES: &[&str] = &[];
pub const SCOPE_TYPES: &[ScopeTypeRow] = &[];
pub const DATA_FNS: &[DataFnRow] = &[];
