//! Golden-tree tests: the Rust parser's rendered tree must match the shared
//! `testdata/*.golden` files (generated by the Go parser). Reuses the repository
//! fixtures directly — they are not copied into the crate.

use std::path::PathBuf;

use pdxl_parser::{parse, render_tree, validate_tree};

fn repo_root() -> PathBuf {
    let mut dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    loop {
        if dir.join("Cargo.toml").is_file() && dir.join("crates").is_dir() {
            return dir;
        }
        assert!(dir.pop(), "could not locate repo root");
    }
}

#[test]
fn golden_trees_match() {
    let testdata = repo_root().join("testdata");
    let mut fixtures: Vec<PathBuf> = std::fs::read_dir(&testdata)
        .expect("read testdata")
        .flatten()
        .map(|e| e.path())
        .filter(|p| p.extension().and_then(|e| e.to_str()) == Some("txt"))
        .collect();
    fixtures.sort();
    assert!(!fixtures.is_empty(), "no fixtures found");

    let mut compared = 0;
    for fixture in &fixtures {
        let name = fixture.file_stem().unwrap().to_string_lossy().to_string();
        let golden_path = testdata.join(format!("{name}.golden"));
        if !golden_path.is_file() {
            continue; // not all fixtures have a golden tree
        }
        let src = std::fs::read(fixture).expect("read fixture");
        let parsed = parse(name.clone(), src);

        // The Go golden test asserts these fixtures parse with zero diagnostics.
        assert!(
            parsed.diagnostics().is_empty(),
            "{name}: unexpected diagnostics: {:?}",
            parsed.diagnostics()
        );
        validate_tree(parsed.tree()).unwrap_or_else(|e| panic!("{name}: invalid tree: {e:?}"));

        let rendered = render_tree(parsed.tree());
        let golden = std::fs::read(&golden_path).expect("read golden");
        assert!(
            rendered == golden,
            "{name}: rendered tree does not match golden\n--- rendered ---\n{}\n--- golden ---\n{}",
            String::from_utf8_lossy(&rendered),
            String::from_utf8_lossy(&golden),
        );
        compared += 1;
    }
    assert!(
        compared >= 8,
        "expected at least 8 golden fixtures, got {compared}"
    );
    eprintln!("golden: {compared} fixtures match the shared .golden files");
}
