[workspace]
resolver = "2"
members = [
    "crates/pdxl-source",
    "crates/pdxl-lexer",
    "crates/pdxl-syntax",
    "crates/pdxl-files",
]

[workspace.package]
edition = "2024"
license = "MIT"
repository = "https://github.com/unlomtrois/pdxl"
rust-version = "1.96"

[workspace.dependencies]
pdxl-source = { path = "crates/pdxl-source" }
pdxl-lexer = { path = "crates/pdxl-lexer" }
pdxl-syntax = { path = "crates/pdxl-syntax" }
