//! CK3 script-documentation tables, generated from the game's own dumps.
//!
//! The row types here are handwritten; the `pub mod` files are GENERATED by
//! `pdxl-gamedocs`' `gen-tables` binary from the logs the game writes to its
//! user directory (`effects.log`, `triggers.log`, `event_targets.log`,
//! `event_scopes.log`, `modifiers.log`). Regenerate after a game patch and
//! review the diff like a golden file — never edit the generated files.
//!
//! Scope names are kept as verbatim strings from the dumps; how to represent
//! them (bitflags, interning) is the future scope engine's decision. These
//! tables are the *data* half of scope awareness (tiger keeps the equivalent
//! ~5k lines hand-transcribed); the *engine* half — effect/trigger context
//! classification and scope-chain resolution — builds on top of them.

/// One effect or trigger: the scopes it is legal in and, for iterators,
/// the element scope it yields.
#[derive(Clone, Copy, Debug)]
pub struct DocRow {
    pub name: &'static str,
    /// Human-readable usage notes from the game's documentation dump.
    pub description: &'static str,
    /// `Supported Scopes:` verbatim (`"none"` = no scope requirement).
    pub scopes: &'static [&'static str],
    /// `Supported Targets:` — for `any_*` iterators, the element scope.
    pub targets: &'static [&'static str],
}

/// One scope-transition link (`event_targets.log`): `title:` / `.holder` /
/// `scope:` style navigation.
#[derive(Clone, Copy, Debug)]
pub struct LinkRow {
    pub name: &'static str,
    /// Takes a `:key` argument (`title:e_hre`, `character:1234`).
    pub requires_data: bool,
    /// Usable from any scope; otherwise `input_scopes` constrains it.
    pub global_link: bool,
    pub wildcard: bool,
    pub input_scopes: &'static [&'static str],
    pub output_scopes: &'static [&'static str],
}

/// One scope type from the game's scope-type registry (`event_scopes.log`).
#[derive(Clone, Copy, Debug)]
pub struct ScopeTypeRow {
    pub name: &'static str,
    pub evaluate_triggers: bool,
    pub execute_effects: bool,
    pub change_scopes: bool,
    pub save_token: Option<&'static str>,
    pub stores_variables: bool,
}

/// One permanent stat modifier (`modifiers.log`).
#[derive(Clone, Copy, Debug)]
pub struct ModifierRow {
    /// May be templated (`$TRAIT_TRACK$_xp_gain_mult`).
    pub tag: &'static str,
    pub use_areas: &'static [&'static str],
}

// The datafunction row/kind types live in `pdxl-gui` (the machinery that
// consumes them); the generated table re-uses them via this re-export.
pub use pdxl_gui::datafn::{DataFnKind, DataFnRow};

pub mod data_types;
pub mod effects;
pub mod modifiers;
pub mod scope_links;
pub mod scope_types;
pub mod triggers;

pub use data_types::DATA_FNS;
pub use effects::EFFECTS;
pub use modifiers::MODIFIERS;
pub use scope_links::{CODE_SAVED_SCOPES, SCOPE_LINKS};
pub use scope_types::SCOPE_TYPES;
pub use triggers::TRIGGERS;
