//! CK3 script-documentation tables, generated from the game's own dumps.
//!
//! The row types here are handwritten; the `pub mod` files are GENERATED by
//! `pdxl-gamedocs`' `gen-tables` binary from the logs the game writes to its
//! user directory (`effects.log`, `triggers.log`, `event_targets.log`,
//! `event_scopes.log`, `modifiers.log`). Regenerate after a game patch and
//! review the diff like a golden file — never edit the generated files.
//!
//! Scope names are kept as verbatim strings from the dumps; how to represent
//! them (bitflags, interning) is the future scope engine's decision. These
//! tables are the *data* half of scope awareness (tiger keeps the equivalent
//! ~5k lines hand-transcribed); the *engine* half — effect/trigger context
//! classification and scope-chain resolution — builds on top of them.

pub use pdxl_gamedocs::rows::{DocRow, LinkRow, ModifierRow, ScopeTypeRow};

// The datafunction row/kind types live in `pdxl-gui` (the machinery that
// consumes them); the generated table re-uses them via this re-export.
pub use pdxl_gui::datafn::{DataFnKind, DataFnRow};

pub mod data_types;
pub mod effects;
pub mod modifiers;
pub mod scope_links;
pub mod scope_types;
pub mod triggers;

pub use data_types::DATA_FNS;
pub use effects::EFFECTS;
pub use modifiers::MODIFIERS;
pub use scope_links::{CODE_SAVED_SCOPES, SCOPE_LINKS};
pub use scope_types::SCOPE_TYPES;
pub use triggers::TRIGGERS;
